### ISSUE TITLE
NodeJS DB Connection

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#12]
**Description**
Make a connection with the database through Node.JS

**Tasks**
- [x] Run Node.JS
- [x] Follow a foundations tutorial for Node.JS
- [x] Understand how DB connections work with Node.JS
- [x] Connect DB through Node.JS

**Sources**
[Node tutorial](https://www.w3schools.com/nodejs/)
[Node DB connection](http://www.tutorialsteacher.com/nodejs/access-sql-server-in-nodejs)

**Comment by vQFire** [comment]
I personnaly am able to do these tasks please look at the new issue I created.

**Comment by AjobK** [comment]
This issue is not needed. Only one issue needed in which the back-end setup and first crud are included. This will be done by Youp.
