### ISSUE TITLE
Read passage about Athena from mythology

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#13]
**Description**
Understand why Athena will be called Athena

**Tasks**
- [x] Ajob read the passage
- [ ] Miguel read the passage
- [ ] Jonah read the passage
- [ ] Youp read the passage
- [ ] Sam read the passage

**Sources**
Request book from @AjobK
