### ISSUE TITLE
Add basic statistics

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#14]
**Description**
Add basic statistics to Athena in order to get information from the get-go

**Tasks**
- [ ] Research which statistics are important
- [ ] Put in comments what BASIC statistics you are going to add
- [ ] Make DB structure for statistics
- [ ] Save statistics
- [ ] Test if statistics are working

**Sources**
¯\\\_(ツ)\_/¯
