### ISSUE TITLE
Setup Waffle

### ISSUE THREAD

**Issue by MiguelFieira** [AjobK/Athena#16]
**Description**
Add an linters to keep Athena clean from messy code (You are a hero if you do this).

**Tasks**
- [ ] Raise Funds for Waffle (**$5,-** per month **$60,-** a year =  **€52,49**)
- [ ] Update the wiki with Git-Workflow
- [ ] Clean up waffle

**Sources**
[Waffel](https://waffle.io/)
