### ISSUE TITLE
Like posts

### ISSUE THREAD

**Issue by jerohero** [AjobK/Athena#192]
**Current state**
There is no back-end or front-end for liking posts within the application

**Expected state**
There is a back-end or front-end for liking posts within the application

**Todo**
Backend
- [x] Creating table for likes
- [x] Creating update likes functionality in post DAO

Frontend
- [x] Implementing styling
- [x] Implementing frontend like functionality

**Necessities**
n/a

**Branch**
192-like-posts
