### ISSUE TITLE
[198] View Liked Posts On Profile

### ISSUE THREAD

**Issue by jerohero** [AjobK/Athena#198]
**Current state**
There is no back-end functionality for fetching all posts a user liked, and this isn't shown on the profile page.

**Expected state**
Users can view their liked posts on their profiles.

**Todo**
Backend
- [ ] Fetching liked posts of a user

Frontend
- [ ] Showing liked posts in frontend
- [ ] Show amount of likes for these posts

**Necessities**
n/a

**Branch**
198-view-liked-posts
