### ISSUE TITLE
[361] Pre-release 1

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#361]
![image](https://user-images.githubusercontent.com/35965716/145713287-76634e17-8188-4e38-b57b-de4dfbbe93ba.png)

**Release description**

All features for release 1 are ready. To deploy this release to master we need to work on the issues below.

**TODO**

Security
- [ ] Refresh token
- [ ] #381
- [x] #327 
- [ ] XSS, SQLInjection, CSRF tokens?
- [ ] #332 
- [ ] Numeric IDs for roles to UUID
- [x] Password toggle visible icon
- [ ] When retrieving post/comments you see user IDs and post IDs. Hide all visible IDs
- [ ] Exclude entity properties such as IDs that are only used for joins
- [ ] npm audit front-end (Dependency OWASP)
- [ ] npm audit back-end (Dependency OWASP)

Other release requirements
- [ ] Perma remove table title
- [ ] Perma remove table title_owned_by
- [ ] Perma remove table archivedPost
- [ ] Perma remove table post_has_attachment
- [ ] Remove until necessary table comment_has_attachment
- [ ] Remove until necessary table email_verfication
- [ ] Translate all Dutch database properties to English
- [ ] No unhandled promise rejections due to response without return

**Comment by AjobK** [comment]
![image](https://user-images.githubusercontent.com/35965716/154845003-b5cea68a-88df-4f97-b45d-a6bed6b8c29e.png)

**Comment by AjobK** [comment]
![image](https://user-images.githubusercontent.com/35965716/154845008-a5b579c7-93b2-4c5b-a7e6-2be63fa1129a.png)

**Comment by AjobK** [comment]
[Seaqull_-_Alfa_1_and_after_UPDATED.pdf](https://github.com/AjobK/Seaqull/files/8104054/Seaqull_-_Alfa_1_and_after_UPDATED.pdf)
