### ISSUE TITLE
Implement Ajax

### ISSUE THREAD

**Issue by MiguelFieira** [AjobK/Athena#49]
## Implement Ajax
We want to be able to save and fetch content from our backend.

**Branch: ```49-ajax ```**

### Tasks **(D.O.D)**
-  **Home Page**
    - [ ] Infinate scrol
    - [x] Fetch Post Titles from DB
    - [ ] Link Posts to correct Page
- **Post Page**
    - [ ] Fetch correct **Post data**
    - [ ] Show concent with the correct styling **(Markdown)**
    - [ ] Save data to the DB 
- **Profile Page**
    - [ ] Fetch correct **User data**
