### ISSUE TITLE
Make the linting more aggressive

### ISSUE THREAD

**Issue by MiguelFieira** [AjobK/Athena#53]
## Description
We need to write more clean code and the linting is not up to standards...
To combat this we need a more aggressive linter to make sure Seaqull code is clean and easy to read!

### Tasks
- [x] Redo Style Linter
- [x] Redo Js Liner
- [x] Make it so that you get an error if you don't do your linting correct
- [x] Recheck all linting from Develop

### D.O.D
Linting should be up to standards and you should get an error until you fix you're linting is correct and up to Seaqull standards.
